<script>
    import Header from '$lib/components/Header.svelte';
</script>

<Header />

<h1>Legal Information</h1>

<p>By using this app, you agree to the terms set out on this page. If you do not agree with these terms, please do not use the app. These terms may be updated at any time without notice.</p>

<h2>Disclaimer</h2>
<p>This app is an unofficial project and is not affiliated with, endorsed by, or supported by the World Cube Association (WCA) in any way.</p>

<p>Answers are generated by an AI model (ChatGPT, via <a href="https://openai.com/api/" target="_blank" rel="noopener noreferrer">OpenAI's API</a>) using the WCA Regulations and Guidelines as a knowledge source. Responses may be incomplete, inaccurate, outdated, or fail to account for the full context of a situation.</p>

<p>While I aim to provide accurate information, I make no guarantees regarding the completeness, reliability, or accuracy of any answer produced by this app.</p>

<p><strong>The official WCA Regulations, WCA Guidelines, and decisions of WCA Delegates remain the authoritative source in all cases.</strong></p>

<p>If you are unsure about a regulation or require an official ruling, consult the latest version of the <a href="https://www.worldcubeassociation.org/regulations/" target="_blank" rel="noopener noreferrer"> WCA Regulations and Guidelines</a> or contact your <a href="https://www.worldcubeassociation.org/delegates" target="_blank" rel="noopener noreferrer">WCA Delegate</a> or <a href="https://www.worldcubeassociation.org/teams-committees#wrc" target="_blank" rel="noopener noreferrer">the WCA Results Committee</a>.</p>

<h2>Acceptable Use</h2>
<p>You may not use this service in a way that interferes with its operation or availability to other users. This includes:</p>
<ul>
    <li>Attempting to disrupt or overload the service.</li>
    <li>Using automated tools (e.g. bots, scrapers) to access the service without permission.</li>
    <li>Miscellaneous activities that violate the terms of service or intentionally impact the service's performance.</li>
</ul>

<p>Abusive, automated, or excessive use of the service may result in access being restricted or blocked without notice. The app automatically limits the number of requests per IP address to 30 per hour.</p>

<h2>Privacy</h2>

<p>Questions submitted to the app (along with IP address, timestamp, and AI-generated responses) are logged for debugging, service improvement, and abuse prevention purposes. Users should not submit personal, confidential, or sensitive information.</p>

<p>This app is hosted on Render on Cloudflare. Their privacy policies can be found <a href="https://render.com/privacy" target="_blank" rel="noopener noreferrer">here</a> and <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">here</a>.</p>